"""
Master dictionary of technology skills and their categories.

Used by SkillExtractor to scan job descriptions for known skill mentions.
Each key is a category label; each value is a list of skill strings.

Guidelines:
    - All skill strings are lowercase.
    - Multi-word skills (e.g. "github actions") use spaces.
    - The regex engine wraps each skill in \\b word-boundary assertions so
      short terms like "r" or "go" do not produce false positives inside
      longer words such as "docker" or "algorithm".
"""

SKILLS_DICT: dict[str, list[str]] = {
    "language": [
        "python",
        "r",
        "sql",
        "scala",
        "java",
        "julia",
        "bash",
        "c++",
        "c#",
        "go",
        "rust",
        "typescript",
        "javascript",
        "matlab",
        "perl",
        "swift",
        "kotlin",
    ],
    "ml_framework": [
        "pytorch",
        "tensorflow",
        "keras",
        "scikit-learn",
        "xgboost",
        "lightgbm",
        "catboost",
        "jax",
        "mxnet",
        "paddle",
        "fastai",
        "onnx",
        "triton",
    ],
    "mlops": [
        "mlflow",
        "kubeflow",
        "airflow",
        "prefect",
        "dvc",
        "bentoml",
        "seldon",
        "ray",
        "weights and biases",
        "wandb",
        "zenml",
        "metaflow",
        "feast",
        "evidently",
        "great expectations",
    ],
    "data_engineering": [
        "spark",
        "kafka",
        "dbt",
        "flink",
        "hadoop",
        "databricks",
        "snowflake",
        "bigquery",
        "redshift",
        "hive",
        "presto",
        "trino",
        "fivetran",
        "stitch",
        "dagster",
        "luigi",
        "nifi",
        "delta lake",
        "iceberg",
    ],
    "cloud": [
        "aws",
        "azure",
        "gcp",
        "s3",
        "ec2",
        "lambda",
        "sagemaker",
        "vertex ai",
        "azure ml",
        "google cloud",
        "cloudformation",
        "cdk",
        "pulumi",
        "cloud run",
        "ecs",
        "eks",
        "aks",
        "gke",
    ],
    "devops": [
        "docker",
        "kubernetes",
        "terraform",
        "github actions",
        "jenkins",
        "helm",
        "ansible",
        "gitlab ci",
        "circle ci",
        "argocd",
        "prometheus",
        "grafana",
        "datadog",
        "new relic",
    ],
    "database": [
        "postgresql",
        "mysql",
        "mongodb",
        "redis",
        "elasticsearch",
        "cassandra",
        "neo4j",
        "dynamodb",
        "cosmos db",
        "firestore",
        "sqlite",
        "mariadb",
        "oracle",
        "mssql",
        "clickhouse",
        "pinecone",
        "weaviate",
        "qdrant",
        "chroma",
    ],
    "nlp": [
        "huggingface",
        "transformers",
        "bert",
        "gpt",
        "langchain",
        "spacy",
        "nltk",
        "llm",
        "rag",
        "llama",
        "mistral",
        "openai",
        "anthropic",
        "embeddings",
        "vector database",
        "semantic search",
        "fine-tuning",
        "lora",
        "qlora",
        "instruction tuning",
    ],
    "visualisation": [
        "tableau",
        "power bi",
        "streamlit",
        "plotly",
        "grafana",
        "superset",
        "looker",
        "matplotlib",
        "seaborn",
        "dash",
        "d3",
        "qlik",
        "metabase",
        "redash",
    ],
    "api": [
        "fastapi",
        "flask",
        "django",
        "rest api",
        "graphql",
        "grpc",
        "celery",
        "rabbitmq",
        "websockets",
        "openapi",
    ],
    "other": [
        "git",
        "linux",
        "agile",
        "jira",
        "jupyter",
        "numpy",
        "pandas",
        "scipy",
        "statsmodels",
        "hypothesis testing",
        "a/b testing",
        "bayesian",
        "time series",
        "computer vision",
        "reinforcement learning",
        "feature engineering",
        "model deployment",
        "ci/cd",
        "tdd",
        "microservices",
        "event-driven",
        "data lake",
        "data warehouse",
        "data mesh",
        "data governance",
    ],
}

# Flat mapping of skill -> category for fast lookup during extraction
SKILL_TO_CATEGORY: dict[str, str] = {
    skill: category
    for category, skills in SKILLS_DICT.items()
    for skill in skills
}
